version: 2.1

orbs:
  cache: https://raw.githubusercontent.com/circleci-petri/caching/refs/heads/main/orbs/build-tool-cache.yml

jobs:
  gradle:
    docker:
      - image: cimg/openjdk:25.0
    environment:
      GRADLE_OPTS: -Dorg.gradle.welcome=never
    steps:
      - run:
          name: Clone WorldEdit
          command: |
            git clone --depth=1 --branch version/7.4.x https://github.com/EngineHub/WorldEdit ~/worldedit
      - run: whoami
      - run: ls -ahl /tmp
      - cache/with_build_tool_cache:
          tool: gradle
          steps:
            - run:
                name: Build
                working_directory: ~/worldedit
                command: ./gradlew --no-daemon --build-cache compileJava
      - run:
          name: Check /tmp
          command: ls -ahl /tmp
          when: always

workflows:
  demo:
    jobs:
      - gradle
      - gradle:
          name: gradle-rerun
          requires:
            - gradle
